version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App_Part2"
    links:
      - db
    ports:
      - "5030:5030"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database_Part2"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro